config/routes.rb
  Handraise::Application.routes.draw do

  resources :courses do 
    resources :issues, :controller => 'course/issues', except: [:index]
  end

  post 'courses/:course_id/issues/:id/queue' => 'course/issues#queue_item', as: 'queue_item'
  post 'courses/:course_id/refresh' => 'courses#refresh'


  get 'courses/:course_id/issues/:id/resolve' => 'course/issues#resolve', :as => 'resolve_issue'
  post 'courses/:course_id/issues/:id/response' => 'responses#create', :as => 'add_response'
  
  get 'courses/:course_id/issues/:id/add_to_queue' => 'course/issues#add_to_queue', :as => 'add_to_queue'
  get 'courses/:course_id/issues/:id/remove_from_queue' => 'course/issues#remove_from_queue', :as => 'remove_from_queue'

  get 'add_primary_course' => 'courses#add_primary_course'
  get 'remove_primary_course' => 'courses#remove_primary_course'

  get 'courses/:course_id/archive' => 'courses#show_archive', :as => 'show_archive'

  get 'add-admin' => 'site#new_admin'
  post 'add-admin' => 'site#create_admin'

  get "sessions/create"
  get "sessions/destroy"
  get "site/start"
  root 'courses#index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :signout  

  
  # OMNIAUTH
  get '/auth/github/' => redirect('/auth/github')
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')

end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id            :integer          not null, primary key
#  description   :text
#  resolved      :integer          default(0)
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  title         :string(255)
#  anonymous     :boolean          default(FALSE)
#  course_id     :integer
#  instructor_id :integer
#  archived      :boolean          default(FALSE)
#

class Issue < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :responses
  #has_many :user_notifications
  
  validates_presence_of :title, message: "Issues Must Have A Title."
  scope :resolved, -> { where(:resolved => 1) }
  scope :unresolved, -> { where(:resolved => 0) }
  scope :not_queued, -> { where(:instructor_id => nil) }
  scope :in_instructor_queue, ->(user) { where(:instructor_id => user.id) }
  scope :archived, -> { where(:archived => true) }
  scope :not_archived, -> { where(:archived => false) }

  def resolved?
    self.resolved > 0 
  end

  def resolve!
    self.resolved = 1
    self.save
  end

  def add_response(user,response_hash)
    response = self.responses.build(response_hash)
    response.user = user
    response
  end
  
  def archived?
    self.archived
  end

  # def notify_preference
  #   self.user_notifications.where(:user_id => self.user_id, :issue_id => self.id).first.notify
  # end

end

app/controllers/course/issues_controller.rb
class Course::IssuesController < ApplicationController
  before_action :set_course
  before_action :set_issue, except: [:new, :create]

  def show
    # if @issue.instructor_id
    #   @remove_from_queue
    # else
    #   @add_to_queue
    # end
    @response = Response.new
  end

  def new
    @issue = Issue.new
    #@user_notification = UserNotification.new
  end

  def create
    @issue = @course.add_issue(current_user, issue_params)

    @issue.notify = params[:issue][:notify]

    if @issue.save
      redirect_to @course, :notice => "Added the issue \"#{@issue.title}\""
    else
      render :new, :notice => "Oops, look like something went wrong :-/"
    end
  end

  def edit
  end

  def update
    @issue.update(issue_params)
    # @user_notification = @issue.user_notifications.where(:user_id => @issue.user_id, :issue_id => @issue.id).first

    @issue.notify = params[:issue][:notify]

    if @issue.save
      redirect_to course_issue_path(@course, @issue), :notice => "Updated the issue: \"#{@issue.title}\""
    else
      render :edit, :notice => "Oops, looks like there was an error :-/"
    end
  end

  def resolve
    @issue.resolve!
    redirect_to @course, :notice => "Resolved!"
  end

  def add_to_queue
      @issue.instructor_id = current_user.id
      @issue.save 
    redirect_to @course, :notice => "Added to #{current_user.name}'s queue"
  end

  def remove_from_queue
      @issue.instructor_id = nil
      @issue.save 
    redirect_to @course, :notice => "Issue removed from #{current_user.name}'s queue"
  end

  private
  def set_issue
    @issue = Issue.find_by(:id => params[:id])
  end

  def set_course
    @course = Course.find_by(:id => params[:course_id])
  end

  def issue_params
    params.require(:issue).permit(:title,:description,:anonymous)
  end

end

app/helpers/course/issues_helper.rb
module Course::IssuesHelper

  def issue_poster_name(issue)
    if current_user.admin || issue.user == current_user
      display_name(issue.user)
    elsif issue.anonymous
      "Anonymous"
    else
      display_name(issue.user)
    end
  end

  def can_see_resolve_button?(issue)
    !issue.resolved? && !issue.archived? && (current_user == issue.user || current_user.admin)
  end

  def issue_name(issue)
    content_tag(:li, "#{issue_poster_name(issue)}", :class => "issue-poster-name")
  end

  def issue_time_ago(issue)
    content_tag(:li, "#{time_ago_in_words(issue.created_at, :seconds => true )} ago", :class => "issue-time-ago")
  end

  def issue_name_and_time_ago(issue)
    content_tag(:li, "#{issue_poster_name(issue)}, #{time_ago_in_words(issue.created_at, :seconds => true )} ago")
  end

  def added_to_instructor_queue(issue)
    if issue.instructor_id && current_user.id != issue.instructor_id
      instructor = User.find(issue.instructor_id)
      content_tag(:li, "In #{instructor.name}'s Queue", :class => "important")
    end
  end

  def format_and_sanitize_text(text)
    add_links = auto_link(text, :sanitize => false)
    add_formatting = simple_format(add_links, {}, :sanitize => false).html_safe 
    #remove_unsafe_markup = sanitize(add_formatting, :tags => %w(p pre a % %= tr td @))
  end


end

app/helpers/issues_helper.rb
module IssuesHelper

  def issue_poster_name(issue)  
    if current_user.admin || current_user == issue.user
      display_name(issue.user)
    elsif issue.anonymous
      "Anonymous"
    else
      display_name(issue.user)
    end
  end

  def can_see_resolve_button?(issue)
    !@issue.resolved? && (current_user == issue.user || current_user.admin)
  end

end

app/views/issues/_form.html.erb
<%= form_for @issue, :html => {:role => "form"}  do |f| %>
  <div class="form-group">
  <%= f.text_field :title, placeholder:"Title", class:"form-control" %>
  <p class="errors"><%= @issue.errors.messages[:title][0] %></p>
  </div>
  <div class="form-group">
  <%= f.text_area :description, placeholder:"Description (optional)", class:"form-control", rows:"4" %>
  </div>
  <div class="radio"> 
  <%= f.radio_button :anonymous, :false, :checked => true %>
  <%= f.label :anonymous, "Post anonymously", :value => 'false' %>
  </div>
   <div class="radio">
  <%= f.radio_button :anonymous, :true %>   
  <%= f.label :anonymous, "Display my name", :value => 'true' %>
   </div>
  <%= f.submit class:"btn btn-primary" %>
<% end %>

app/views/issues/index.html.erb
<% if current_user.admin %>
<h1><%= current_user.name%>'s queue</h1>
<% if @instructor_queue.count == 0 %>
  <p>There are currently no items in your queue.</p>
<% else %>
<ul class="issues-list">
  <% @instructor_queue.each do |issue| %>
  <li>
    <a href="<%= issue_path(issue) %>" title="<%= issue.title.titleize %>"><%= issue.title.capitalize %>
      <div class="pull-right">
        <ul class="meta-info">
          <li><%= issue_poster_name(issue) %>,</li>
          <li><%= time_ago_in_words(issue.created_at, :seconds => true ) %> ago</li>
          <li>&nbsp;&nbsp;</li>
          <% if issue.responses.count > 0 %>
          <li><span class="label label-default">
            <span class="glyphicon glyphicon-comment"></span>
            <%= pluralize(issue.responses.count, 'Reply') %></span>
          </li>
          <% end %>
        </ul>
      </div>
    </a>
  </li>
  <% end %>
</ul>
<% end %>

<% else %>
  <div class="row list-header">
    <div class="col-sm-12">
      <%= link_to "New issue", new_issue_path, class:"btn btn-default pull-right action-button" %>
      <h1>Open Issues</h1>
    </div>
  </div>
<% end %>

<div class="row">
  <div class="col-sm-12">
    <ul class="issues-list">
      <% @unresolved_issues.each do |issue| %>
      <li>
        <a href="<%= issue_path(issue) %>" title="<%= issue.title.titleize %>"><span class="issue-title"><%= issue.title.titleize %></span>
            <ul class="meta-info">
              <li><%= issue_poster_name(issue) %>,</li>
              <li><%= time_ago_in_words(issue.created_at, :seconds => true ) %> ago</li>
              <li>&nbsp;&nbsp;</li>
              <% if issue.responses.count > 0 %>
              <li><span class="label label-default">
                <span class="glyphicon glyphicon-comment">
                </span>
                <%= pluralize(issue.responses.count, 'Reply') %>
              </span></li>
              <% end %>
            </ul>
        </a>
      </li>
      <% end %>
    </ul>
  </div>
</div>
<% if @resolved_issues.count > 0 %>
<div class="row list-header">
    <div class="col-sm-12">
      <h1>Archived Issues</h1>
    </div>
  </div>
<ul class="button-list">
  <% @resolved_issues.each do |issue| %>
  <li><%= link_to "#{issue_poster_name(issue)}: #{issue.title.titleize} (#{pluralize(issue.responses.count, 'response')})", issue %></li>
  <% end %>
</ul>
<% end %>

app/views/issues/show.html.erb
<div class="row list-header">
  <div class="col-sm-12">
    <h1><%= @issue.title.capitalize %></h1>
  </div>
</div>
<p><%= auto_link(simple_format(@issue.description)) %></p>
<ul class="pull-right inline-list">
  <% if current_user.id == @issue.user_id %>
  <li><a class="btn btn-default btn-xs" href="<%= edit_issue_path(@issue) %>" role="button", class:"btn btn-default"><span class="glyphicon glyphicon-edit"></span> Edit</a></li>
  <% end %>
  <% if current_user.admin %>
    <% if @issue.instructor_id %>
    <li><a class="btn btn-default btn-xs" href="<%= remove_from_queue_path(@issue) %>" role="button", class:"btn btn-default">Remove from my queue <span class="glyphicon glyphicon-minus-sign"></span></a></li>
    <% else %>
    <li><a class="btn btn-default btn-xs" href="<%= add_to_queue_path(@issue) %>" role="button", class:"btn btn-default">Add to my queue <span class="glyphicon glyphicon-plus-sign"></span></a></li>
    <% end %>
  <% end %>
  <% if can_see_resolve_button?(@issue) %>
  <li><a class="btn btn-default btn-xs" href="<%= resolve_path(@issue) %>" role="button", class:"btn btn-default">Archive <%= image_tag("archive_noun_project_svg_14744.svg", :alt => "Archive icon", :size => "12x12", style:"margin-top:-3px;") %> </a>
  </li>
  <% end %>
</ul>

<ul class="inline-list meta-info">
  <li><%= issue_poster_name(@issue) %></li>
  <li><%= time_ago_in_words(@issue.created_at, :seconds => true ) %> ago</li>
</ul>
<div class="issue-replies">
  <div class="list-header">
    <h2>Replies</h2> 
  </div>
  <% if @issue.responses.any? %>
  <ul class="no-bullets">
    <% @issue.responses.each do |response| %>
    <li>
      <p><%= image_tag(current_user.image_gravatar, :alt => "Gravatar", class:"gravatar") %> <%= display_name(response.user)%>, <%= time_ago_in_words(response.created_at, :seconds => true ) %> ago:</p>
      <blockquote>
        <%= auto_link(simple_format(response.description)) %>
      </blockquote>
    </li>
    <% end %>
  </ul>
  <% end %>
  <%= render "responses/new" %>
</div>