config/routes.rb
  Handraise::Application.routes.draw do

  resources :courses do 
    resources :issues, :controller => 'course/issues', except: [:index]
  end

  post 'courses/:course_id/issues/:id/queue' => 'course/issues#queue_item', as: 'queue_item'
  post 'courses/:course_id/refresh' => 'courses#refresh'


  get 'courses/:course_id/issues/:id/resolve' => 'course/issues#resolve', :as => 'resolve_issue'
  post 'courses/:course_id/issues/:id/response' => 'responses#create', :as => 'add_response'
  
  get 'courses/:course_id/issues/:id/add_to_queue' => 'course/issues#add_to_queue', :as => 'add_to_queue'
  get 'courses/:course_id/issues/:id/remove_from_queue' => 'course/issues#remove_from_queue', :as => 'remove_from_queue'

  get 'add_primary_course' => 'courses#add_primary_course'
  get 'remove_primary_course' => 'courses#remove_primary_course'

  get 'courses/:course_id/archive' => 'courses#show_archive', :as => 'show_archive'

  get 'add-admin' => 'site#new_admin'
  post 'add-admin' => 'site#create_admin'

  get "sessions/create"
  get "sessions/destroy"
  get "site/start"
  root 'courses#index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :signout  

  
  # OMNIAUTH
  get '/auth/github/' => redirect('/auth/github')
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')

end

app/models/course.rb
# == Schema Information
#
# Table name: courses
#
#  id         :integer          not null, primary key
#  name       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Course < ActiveRecord::Base
  has_many :issues
  has_many :responses, :through => :issues
  validates_presence_of :name, message: "Courses must have a name."
  validates :name, length: {maximum: 20, too_long: "Sorry, course names can have no more than 20 characters."}


  def add_issue(user,issue_hash)
    issue = self.issues.build(issue_hash)
    issue.user = user
    issue
    #returns an unsaved issue, so that the controller can attempt to save it, and then see if there are any errors
  end
end

app/models/issue.rb
# == Schema Information
#
# Table name: issues
#
#  id            :integer          not null, primary key
#  description   :text
#  resolved      :integer          default(0)
#  user_id       :integer
#  created_at    :datetime
#  updated_at    :datetime
#  title         :string(255)
#  anonymous     :boolean          default(FALSE)
#  course_id     :integer
#  instructor_id :integer
#  archived      :boolean          default(FALSE)
#

class Issue < ActiveRecord::Base
  belongs_to :user
  belongs_to :course
  has_many :responses
  #has_many :user_notifications
  
  validates_presence_of :title, message: "Issues Must Have A Title."
  scope :resolved, -> { where(:resolved => 1) }
  scope :unresolved, -> { where(:resolved => 0) }
  scope :not_queued, -> { where(:instructor_id => nil) }
  scope :in_instructor_queue, ->(user) { where(:instructor_id => user.id) }
  scope :archived, -> { where(:archived => true) }
  scope :not_archived, -> { where(:archived => false) }

  def resolved?
    self.resolved > 0 
  end

  def resolve!
    self.resolved = 1
    self.save
  end

  def add_response(user,response_hash)
    response = self.responses.build(response_hash)
    response.user = user
    response
  end
  
  def archived?
    self.archived
  end

  # def notify_preference
  #   self.user_notifications.where(:user_id => self.user_id, :issue_id => self.id).first.notify
  # end

end

app/controllers/course/issues_controller.rb
class Course::IssuesController < ApplicationController
  before_action :set_course
  before_action :set_issue, except: [:new, :create]

  def show
    # if @issue.instructor_id
    #   @remove_from_queue
    # else
    #   @add_to_queue
    # end
    @response = Response.new
  end

  def new
    @issue = Issue.new
    #@user_notification = UserNotification.new
  end

  def create
    @issue = @course.add_issue(current_user, issue_params)

    @issue.notify = params[:issue][:notify]

    if @issue.save
      redirect_to @course, :notice => "Added the issue \"#{@issue.title}\""
    else
      render :new, :notice => "Oops, look like something went wrong :-/"
    end
  end

  def edit
  end

  def update
    @issue.update(issue_params)
    # @user_notification = @issue.user_notifications.where(:user_id => @issue.user_id, :issue_id => @issue.id).first

    @issue.notify = params[:issue][:notify]

    if @issue.save
      redirect_to course_issue_path(@course, @issue), :notice => "Updated the issue: \"#{@issue.title}\""
    else
      render :edit, :notice => "Oops, looks like there was an error :-/"
    end
  end

  def resolve
    @issue.resolve!
    redirect_to @course, :notice => "Resolved!"
  end

  def add_to_queue
      @issue.instructor_id = current_user.id
      @issue.save 
    redirect_to @course, :notice => "Added to #{current_user.name}'s queue"
  end

  def remove_from_queue
      @issue.instructor_id = nil
      @issue.save 
    redirect_to @course, :notice => "Issue removed from #{current_user.name}'s queue"
  end

  private
  def set_issue
    @issue = Issue.find_by(:id => params[:id])
  end

  def set_course
    @course = Course.find_by(:id => params[:course_id])
  end

  def issue_params
    params.require(:issue).permit(:title,:description,:anonymous)
  end

end

app/helpers/course/issues_helper.rb
module Course::IssuesHelper

  def issue_poster_name(issue)
    if current_user.admin || issue.user == current_user
      display_name(issue.user)
    elsif issue.anonymous
      "Anonymous"
    else
      display_name(issue.user)
    end
  end

  def can_see_resolve_button?(issue)
    !issue.resolved? && !issue.archived? && (current_user == issue.user || current_user.admin)
  end

  def issue_name(issue)
    content_tag(:li, "#{issue_poster_name(issue)}", :class => "issue-poster-name")
  end

  def issue_time_ago(issue)
    content_tag(:li, "#{time_ago_in_words(issue.created_at, :seconds => true )} ago", :class => "issue-time-ago")
  end

  def issue_name_and_time_ago(issue)
    content_tag(:li, "#{issue_poster_name(issue)}, #{time_ago_in_words(issue.created_at, :seconds => true )} ago")
  end

  def added_to_instructor_queue(issue)
    if issue.instructor_id && current_user.id != issue.instructor_id
      instructor = User.find(issue.instructor_id)
      content_tag(:li, "In #{instructor.name}'s Queue", :class => "important")
    end
  end

  def format_and_sanitize_text(text)
    add_links = auto_link(text, :sanitize => false)
    add_formatting = simple_format(add_links, {}, :sanitize => false).html_safe 
    #remove_unsafe_markup = sanitize(add_formatting, :tags => %w(p pre a % %= tr td @))
  end


end

app/helpers/issues_helper.rb
module IssuesHelper

  def issue_poster_name(issue)  
    if current_user.admin || current_user == issue.user
      display_name(issue.user)
    elsif issue.anonymous
      "Anonymous"
    else
      display_name(issue.user)
    end
  end

  def can_see_resolve_button?(issue)
    !@issue.resolved? && (current_user == issue.user || current_user.admin)
  end

end

app/views/course/issues/_add_remove_queue_buttons.html.erb
  <%  if current_user == @issue.user %>
    <%= link_to edit_course_issue_path(@course, @issue), :class => 'btn btn-default btn-sm' do %>
      <li><span class="glyphicon glyphicon-edit"></span> Edit</li>
    <% end %>
  <% end %>

  <% if current_user.admin %>
    <% if @issue.instructor_id == current_user.id %>
      <%= link_to remove_from_queue_path(@course, @issue), :class => 'btn btn-default btn-sm' do %>
        <li><span class="glyphicon glyphicon-minus-sign"></span>Remove from my queue</li>
      <% end %>
    <% else %> 
      <%= link_to add_to_queue_path(@course, @issue), :class => 'btn btn-default btn-sm' do %>
        <li><span class="glyphicon glyphicon-plus-sign"></span>Add to my queue</li>
          <% end %>
      <% end %>
  <% end %>

app/views/course/issues/_add_response.html.erb
<p><%= display_gravatar(current_user) %> <%= display_name(current_user)%>:</p>
<%= form_for @response, :url => add_response_path(@course,@issue), :html => {:role => "form", id:"add_response"} do |f| %>
<div class="form-group">
  <%= f.text_area :description, class:"form-control reply-description", placeholder:"Add a reply...", :id => "reply-description"  %>
  <p class="help-text">Some HTML tags allowed.  Insert code snippets using pre tags, eg <span class="code-sample">&#60;pre&#62;a code snippet&#60;/pre&#62;</span>.</p>
  <p class="errors"><%= @response.errors.messages[:description][0] %></p>
  </div>
  <div class="form-group">
  </div>
  <% if @response.errors.any? %>
  <div class="errors">
    <%= @response.errors.first[1] %>
    <br><br>
  </div>
<% end %>
  <%= f.submit "Reply", class:"btn btn-primary reply-submit", :id => "reply-submit" %>
<% end %>

app/views/course/issues/_course_header.html.erb
<div class="row list-header">
  <div class="col-sm-12">
    <h1><%= @issue.title.capitalize %></h1>
  </div>
</div>

app/views/course/issues/_course_info_block.html.erb
<div class="issue-description"><%= format_and_sanitize_text(@issue.description) %></div>   

<%= render 'course_issue_show_buttons' %>

<ul class="inline-list meta-info">
  <li><%= display_gravatar(@issue.user) %>&nbsp;<%= issue_name_and_time_ago(@issue) %></li>
  <%= added_to_instructor_queue(@issue) %>
</ul>

app/views/course/issues/_course_issue_show_buttons.html.erb
<ul class="pull-right inline-list">
  <% if !@issue.archived? %>
      <%= render 'add_remove_queue_buttons' %>
  <% end %>

  <% if can_see_resolve_button?(@issue) %>
    <li>
      <a class="btn btn-default btn-sm" href="<%= resolve_issue_path(@course, @issue) %>" role="button", class:"btn btn-default">Resolve</a>
    </li>
  <% end %>
</ul>

app/views/course/issues/_form.html.erb
<%= form_for [@course, @issue], :html => {:role => "form"}  do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder:"Title", class:"form-control issue-title", :autofocus => true, :id => "issue-title" %>
  <p class="errors"><%= @issue.errors.messages[:title][0] %></p>
</div>
<div class="form-group">
  <%= f.text_area :description, placeholder:"Description (optional)", class:"form-control", rows:"4" %>
  <p class="help-text">Some HTML tags allowed.  Insert code snippets using pre tags, eg <span class="code-sample">&#60;pre&#62;a code snippet&#60;/pre&#62;</span>.</p>
</div>
<div class="radio"> 
  <%= f.radio_button :anonymous, :true, :checked => true %>
  <%= f.label :anonymous, "Post anonymously", :value => 'true' %>
</div>
<div class="radio">
  <%= f.radio_button :anonymous, :false %>   
  <%= f.label :anonymous, "Display my name", :value => 'false' %>
</div>
  <div class="checkbox">
    <%= f.label :notify do %>
      <%= f.check_box :notify, { :checked=> ( @issue.notify ? true : false) } %>
      Notify me when someone replies to this post.
    <% end %>
  </div>
<%= f.submit class:"btn btn-primary issue-submit", :id => "issue-submit" %>
<% end %>

app/views/course/issues/_issue_responses_loop.html.erb
<% if @issue.responses.any? %>
<ul class="no-bullets">
  <% @issue.responses.each do |response| %>
  <li>
    <p><%= display_gravatar(response.user) %> <%= display_name(response.user)%>, <%= time_ago_in_words(response.created_at, :seconds => true ) %> ago:</p>
    <blockquote>
      <%= format_and_sanitize_text(response.description) %>
    </blockquote>
  </li>
  <% end %>
</ul>
<% end %>

app/views/course/issues/_replies_and_responses.html.erb
<div class="issue-replies">
  <div class="list-header">
    <h2>Replies</h2> 
  </div>
  <%= render 'issue_responses_loop' %>
<%= render "add_response" %>
</div>

app/views/course/issues/edit.html.erb
<h1>Edit your issue</h1>
<%= render 'form' %>

app/views/course/issues/new.html.erb
<div class="form-header">
  <h1>New issue</h1>
</div>

<%= form_for [@course, @issue], :html => {:role => "form"}  do |f| %>
<div class="form-group">
  <%= f.text_field :title, placeholder:"Title", class:"form-control issue-title-new", :autofocus => true, :id => "issue-title-new" %>
  <p class="errors"><%= @issue.errors.messages[:title][0] %></p>
</div>
<div class="form-group">
  <%= f.text_area :description, placeholder:"Description (optional)", class:"form-control", rows:"4" %>
  <p class="help-text">Some HTML tags allowed.  Insert code snippets using pre tags, eg <span class="code-sample">&#60;pre&#62;a code snippet&#60;/pre&#62;</span>.</p>
</div>
<div class="radio"> 
  <%= f.radio_button :anonymous, :true, :checked => true %>
  <%= f.label :anonymous, "Post anonymously", :value => 'true' %>
</div>
<div class="radio">
  <%= f.radio_button :anonymous, :false %>   
  <%= f.label :anonymous, "Display my name", :value => 'false' %>
</div>
  <div class="checkbox">
    <%= f.label :notify do %>
      <%= f.check_box :notify, { :checked=> true } %>
      Notify me when someone replies to this post.
    <% end %>
  </div>
<%= f.submit class:"btn btn-primary issue-submit", :id => "issue-submit-new" %>
<% end %>

app/views/course/issues/show.html.erb
<%= render 'course_header' %>

<%= render 'course_info_block' %>

<%= render 'replies_and_responses' %>