config/routes.rb
  Handraise::Application.routes.draw do

  resources :courses do 
    resources :issues, :controller => 'course/issues', except: [:index]
  end

  post 'courses/:course_id/issues/:id/queue' => 'course/issues#queue_item', as: 'queue_item'
  post 'courses/:course_id/refresh' => 'courses#refresh'


  get 'courses/:course_id/issues/:id/resolve' => 'course/issues#resolve', :as => 'resolve_issue'
  post 'courses/:course_id/issues/:id/response' => 'responses#create', :as => 'add_response'
  
  get 'courses/:course_id/issues/:id/add_to_queue' => 'course/issues#add_to_queue', :as => 'add_to_queue'
  get 'courses/:course_id/issues/:id/remove_from_queue' => 'course/issues#remove_from_queue', :as => 'remove_from_queue'

  get 'add_primary_course' => 'courses#add_primary_course'
  get 'remove_primary_course' => 'courses#remove_primary_course'

  get 'courses/:course_id/archive' => 'courses#show_archive', :as => 'show_archive'

  get 'add-admin' => 'site#new_admin'
  post 'add-admin' => 'site#create_admin'

  get "sessions/create"
  get "sessions/destroy"
  get "site/start"
  root 'courses#index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :signout  

  
  # OMNIAUTH
  get '/auth/github/' => redirect('/auth/github')
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')

end

app/controllers/courses_controller.rb
  class CoursesController < ApplicationController
  before_filter :set_course, only: [:show, :edit, :update, :add_to_queue, :remove_from_queue, :show_archive, :refresh]

  def index
    if current_user.primary_course_id
      @course = Course.find_by(:id => current_user.primary_course_id)
      redirect_to @course
    else
      @courses = Course.all
    end
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.new(course_params)

    if @course.save
      redirect_to @course, :notice => "Created!"
    else
      render :new
    end
  end

  def show
    if current_user.admin
      @unresolved_issues = @course.issues.order('created_at DESC').unresolved.not_queued
      @instructor_queue = @course.issues.order('created_at DESC').in_instructor_queue(current_user).unresolved.not_archived
    else
      @unresolved_issues = @course.issues.order('created_at DESC').unresolved
    end

    @resolved_issues = @course.issues.order('created_at DESC').resolved.not_archived
    
  end

  def edit
  end

  def update
    @course.update(course_params)
    if @course.save
      redirect_to @course, :notice => "Edited!"
    else
      render :edit
    end
  end

  def add_primary_course
    @course = Course.find_by(:id => params["course_id"])
    current_user.primary_course_id = params["course_id"]
    current_user.save
    redirect_to @course, :notice => "Primary Course Saved!"
  end

  def remove_primary_course
    @course = Course.find_by(:id => params["course_id"])
    current_user.primary_course_id = nil
    current_user.save
    redirect_to @course, :notice => "Primary Course Removed..."
  end

  def show_archive
    @course = Course.find_by(id: params["course_id"])
    @archived_issues = Issue.where(course_id: params["course_id"]).where(archived: true)
  end

  def refresh
    if current_user.admin = true
     @course = Course.find(params["course_id"])
     @issues = Issue.where(course_id: @course.id)
     render json: @course.issues.to_json(include: [:user, :responses])
    end

  end

  private

  def json_hash
    #returns a hash with all the shit we want to go to javascript.
  end

  def set_course
    @course = Course.find_by(:id => params[:id])
  end

  def course_params
    params.require(:course).permit(:name)
  end

end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_check_for_and_render_primary_course_select.html.erb
<% if @course && /(courses)+.\d/.match(request.env['PATH_INFO']) && request.env['PATH_INFO'].length < 12 %>
  <% if current_user.primary_course_id %>
    <li><%= link_to "Remove #{@course.name} as your primary course.", action: "remove_primary_course", controller: :courses_controller, course_id: @course.id %></li>
  <% else %>
    <li><%= link_to "Add #{@course.name} as your primary course.", action: "add_primary_course", controller: :courses_controller, course_id: @course.id %></li>
  <% end %>
<% end %>

app/views/courses/_enqueue_button.html.erb
<% if issue.instructor_id != current_user.id %>
 <li>
  <%= link_to add_to_queue_path(@course,issue) do %>
    <span class="label label-success">
      <span class="glyphicon glyphicon-plus-sign"></span>
      Enqueue
      </span>
  <% end %>
   </li>
<% end %>

app/views/courses/_enqueue_issue.html.erb
 <li>
  <%= link_to add_to_queue_path(@course,issue) do %>
    <span class="label label-success">
      <span class="glyphicon glyphicon-plus-sign"></span>
      Enqueue
      </span>
  <% end %>
   </li>

app/views/courses/_form.html.erb
<% if @course.errors.any? %>
  <div class="errors">
    <%= @course.errors.first[1] %>
    <br><br>
  </div>
<% end %>

<%= form_for @course, :html => {:role => "form"}  do |f| %>
  <div class="form-group">
  <%= f.text_field :name, placeholder:"Course Name", class:"form-control course-name", :autofocus => true, :id => "course-name" %>
  </div>
  <%= f.submit class:"btn btn-primary course-submit", :id => "course-submit" %>
<% end %>

  

app/views/courses/_instructor_queue.html.erb
<div class="row list-header">
    <div class="col-sm-12">
      <h1><%= display_name(current_user) %>'s Queue</h1>
    </div>
  </div>
<% if @instructor_queue.count == 0 %>
<ul class="issues-list" id="instructor_refresh">
  <li class="no-items">There are currently no items in your queue.</li>
</ul>
<% else %>

<ul class="issues-list" id="instructor_refresh">
  <% @instructor_queue.reverse.each do |issue| %>
    <%= render 'issue_button_link', :issue => issue %>
  <% end %>
</ul>
<% end %>

app/views/courses/_issue_link.html.erb
<li>
<%= link_to course_issue_path @course, issue do %>
<button>
  <span class="issue-title"><%= issue.title.capitalize %></span>
    <ul class="meta-info">
      <%= issue_name(issue) %>
      <%= issue_time_ago(issue) %>
      <%= added_to_instructor_queue(issue) %>
      <%= render 'issue_responses', :count => issue.responses.count if issue.responses.any? %>
        <%= render 'enqueue_issue', :issue => issue if @current_user.admin? && issue.instructor_id != current_user.id %>
    </ul>
</button>
<% end %>
</li>

app/views/courses/_issue_responses.html.erb
<li><span class="label label-default">
  <span class="glyphicon glyphicon-comment">
  </span>
  <%= pluralize(count, 'Reply') %>
</span></li>

app/views/courses/_issue_responses_reply_count.html.erb
<li><span class="label label-default">
  <span class="glyphicon glyphicon-comment">
  </span>
  <%= pluralize(count, 'Reply') %>
</span></li>

app/views/courses/_new_and_unresolved.html.erb
<div class="row list-header">
    <div class="col-sm-12">
    <%= render 'add_issue_unless_admin' %>
      <h1>Open Issues</h1>
    </div>
  </div>

<div class="row">
  <div class="col-sm-12">
  <%= render 'unresolved_issues' %>
  </div>
</div>

app/views/courses/_resolved_issues.html.erb
<% if @resolved_issues.any? %>
  <div class="row list-header">
      <div class="col-sm-12">
        <h1>Resolved Issues</h1>
      </div>
    </div>
  <ul class="button-list" id="resolved_issue_refresh">
    <% @resolved_issues.each do |issue| %>
      <%= render 'resolved_issues_each', :issue => issue %>
    <% end %>
  </ul>
<% end %>

app/views/courses/_unresolved_issues.html.erb
<ul class="issues-list" id="open_issue_refresh">
  <% @unresolved_issues.each do |issue| %>
    <% if !issue.archived? && current_user.admin %>
        <%= render 'issue_button_link', :issue => issue %>
    <% else %>
        <%= render 'issue_button_link', :issue => issue %>
    <% end %>
  <% end %>
</ul>

app/views/courses/edit.html.erb
<h2>Edit your course</h2>
<%= render 'form' %>

app/views/courses/new.html.erb
<h2>New course</h2  >

<%= render 'form' %>

app/views/courses/show.html.erb
<%= render 'instructor_queue' if current_user.admin %>
<%= render 'unresolved_issues' %>
<%  %>
<%= render 'resolved_issues' if @resolved_issues.any? %>