config/routes.rb
  Handraise::Application.routes.draw do

  resources :courses do 
    resources :issues, :controller => 'course/issues', except: [:index]
  end

  post 'courses/:course_id/issues/:id/queue' => 'course/issues#queue_item', as: 'queue_item'
  post 'courses/:course_id/refresh' => 'courses#refresh'


  get 'courses/:course_id/issues/:id/resolve' => 'course/issues#resolve', :as => 'resolve_issue'
  post 'courses/:course_id/issues/:id/response' => 'responses#create', :as => 'add_response'
  
  get 'courses/:course_id/issues/:id/add_to_queue' => 'course/issues#add_to_queue', :as => 'add_to_queue'
  get 'courses/:course_id/issues/:id/remove_from_queue' => 'course/issues#remove_from_queue', :as => 'remove_from_queue'

  get 'add_primary_course' => 'courses#add_primary_course'
  get 'remove_primary_course' => 'courses#remove_primary_course'

  get 'courses/:course_id/archive' => 'courses#show_archive', :as => 'show_archive'

  get 'add-admin' => 'site#new_admin'
  post 'add-admin' => 'site#create_admin'

  get "sessions/create"
  get "sessions/destroy"
  get "site/start"
  root 'courses#index'

  get 'login' => 'sessions#new', as: :login
  get 'logout' => 'sessions#destroy', as: :signout  

  
  # OMNIAUTH
  get '/auth/github/' => redirect('/auth/github')
  get '/auth/github/callback', to: 'sessions#create'
  get '/auth/failure' => redirect('/')

end

app/views/layouts/_check_for_and_render_primary_course_select.html.erb
<% if @course && /(courses)+.\d/.match(request.env['PATH_INFO']) && request.env['PATH_INFO'].length < 12 %>
  <% if current_user.primary_course_id %>
    <li><%= link_to "Remove #{@course.name} as your primary course.", action: "remove_primary_course", course_id: @course.id %></li>
  <% else %>
    <li><%= link_to "Make this your primary course.", action: "add_primary_course", course_id: @course.id %></li>
  <% end %>
<% end %>

app/views/layouts/_flash_message.html.erb
<div class="row">
  <div class="col-sm-12">
    <p class="alert alert-success"><%= flash[:notice] %></p>
  </div>
</div>   

app/views/layouts/_google_analytics.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-47501602-1', 'iqueue.co');
  ga('send', 'pageview');

</script>

app/views/layouts/_navbar.html.erb
 <div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
     <!--<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"> -->
      <!--   <span class="sr-only">Toggle navigation</span> -->
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>

      <%= link_to @course, :class => 'navbar-brand' do %>
        <%= render 'layouts/navbar_content' %>
      <% end %>

    </div>
    <%= render 'layouts/user_display_and_login' if current_user %>
  </div>
</div>

app/views/layouts/_navbar_content.html.erb
<%= image_tag("handraise_noun_project_12043_gray.svg", :alt => "Handraise icon", :size => "25x25", class:"app-brand") %> 

<div class="app-name">
<%= @course && @course.persisted? ? "#{@course.name}" : "Issue Queue" %>
</div>

app/views/layouts/_user_display_and_login.html.erb
<div class="navbar-collapse collapse">
  <ul class="nav navbar-nav navbar-right">
    <li class="dropdown">
    <% #TODO: link to do %>
    <a href="#" class="dropdown-toggle" data-toggle="dropdown">

    <%= display_gravatar(current_user) %> 

    <span class="disappearing-menu">
        <%= display_name(current_user) %>
        <% if current_user.admin %>
        (Instructor)
        <% end %>
    </span>

    <b class="caret"></b>
    </a>
    <ul class="dropdown-menu user-menu prime-menu">
      <li><%= link_to "Sign Out", signout_path %></li>
      <li>
        <% if @course && /(courses)+.\d/.match(request.env['PATH_INFO']) && request.env['PATH_INFO'].length < 12 %>
        <%= link_to "#{@course.name} Archive", show_archive_path(@course) %></li>
        <% end %>
        <%= render 'layouts/check_for_and_render_primary_course_select' %>
    </li>
  </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<% #TODO: extract into method %>
  <title><%= @course && @course.persisted? ? "#{@course.name}" : "Issue Queue" %></title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1, user-scalable=0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <%= favicon_link_tag '/favicon.ico' %>
  <%= favicon_link_tag 'apple-touch-icon.png', :rel => 'apple-touch-icon', :type => 'image/png' %>
   <%= favicon_link_tag 'apple-touch-icon-57x57.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '57x57' %>
  <%= favicon_link_tag 'apple-touch-icon-72x72.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '72x72' %>
   <%= favicon_link_tag 'apple-touch-icon-76x76.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '76x76' %>
  <%= favicon_link_tag 'apple-touch-icon-114x114.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '114x114' %>
   <%= favicon_link_tag 'apple-touch-icon-120x120.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '120x120' %>
  <%= favicon_link_tag 'apple-touch-icon-144x144.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '144x144' %>
   <%= favicon_link_tag 'apple-touch-icon-152x152.png', rel: 'apple-touch-icon', type: 'image/png', sizes: '152x152' %>
</head>
<body>
<%= render 'layouts/navbar' %>

<div class="container padding-on-top">
  <div class="main-content">
    <%= render 'layouts/flash_message' if flash[:notice] %>
    <%= yield %>
  </div>
</div>
<footer>
  &nbsp;
</footer>
<%= render 'layouts/google_analytics' %>
</body>
</html>

app/views/layouts/login.html.erb
  <!DOCTYPE html>
  <html>
  <head>
    <title>Issue Queue</title>
    <%= stylesheet_link_tag    "application", media: "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= favicon_link_tag '/favicon.ico' %> 
  </head>
  <body>
   <!-- Fixed navbar -->
   <%= render 'layouts/navbar' %>


  <div class="container">
   <%= yield %>
 </div> <!-- /container -->
</body>
</html>